# meta_product_name: "StreamDream"
# meta_title: "StreamDream - Find your optimal streaming service."
# meta_description: "Stop wasting time and money scrolling through multiple streaming services. Find your optimal streaming service based on your movie taste."
# meta_image: "Stream-guy.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
